# Generated by Django 3.0.2 on 2020-02-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_add', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=30)),
                ('emplacement', models.CharField(max_length=30)),
                ('mac_add', models.CharField(max_length=30)),
                ('etat', models.CharField(max_length=30)),
                ('aeroport', models.CharField(max_length=30)),
                ('switch', models.CharField(default=0, max_length=30, null=True)),
                ('num_port', models.CharField(default=0, max_length=30, null=True)),
                ('nbre_port', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
