# Generated by Django 3.0.2 on 2020-03-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=20)),
                ('date_panne', models.DateField(max_length=20)),
                ('date_reparation', models.DateField(max_length=20)),
                ('technicien', models.CharField(max_length=20)),
                ('remarque', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='technicien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='equipement',
            name='num_port',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
