# Generated by Django 3.0.2 on 2020-03-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20200315_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panne',
            name='remarque',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
