# Generated by Django 3.0.2 on 2020-03-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20200320_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicien',
            name='cin',
        ),
    ]
