# Generated by Django 3.0.2 on 2020-03-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_remove_technicien_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panne',
            name='remarque',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
