# Generated by Django 3.0.2 on 2020-05-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20200525_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='aeroport',
            field=models.CharField(choices=[('MONASTIR', 'monastir'), ('ENFIDHA', 'enfidha')], default='MONASTIR', max_length=30),
        ),
        migrations.AlterField(
            model_name='panne',
            name='technicien',
            field=models.CharField(choices=[('MAJDI', 'majdi'), ('YASIN', 'yasin')], default='MAJDI', max_length=30),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
