# Generated by Django 3.0.2 on 2020-07-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20200525_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='ip_add',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='panne',
            name='mac_add',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
