# Generated by Django 3.0.2 on 2020-07-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20200709_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panne',
            name='mac_add',
        ),
    ]
