# Generated by Django 3.0.2 on 2020-07-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_remove_panne_mac_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panne',
            old_name='ip_add',
            new_name='ip',
        ),
    ]
