# Generated by Django 3.0.2 on 2020-07-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_auto_20200713_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='idf',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='panne',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
