# Generated by Django 3.0.2 on 2020-07-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_auto_20200714_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panne',
            name='idf',
        ),
    ]
